// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBurWVoIlpJYoWYo7auf_K-Xzz2CvClOS4',
    appId: '1:951154264571:web:5a502397dd8ab678d3e35e',
    messagingSenderId: '951154264571',
    projectId: 'auto-shop-web',
    authDomain: 'auto-shop-web.firebaseapp.com',
    storageBucket: 'auto-shop-web.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6RXywPwTp2UzCz10yjT95lsYwOmlqYF8',
    appId: '1:951154264571:android:c34bc9e7eb21bbc2d3e35e',
    messagingSenderId: '951154264571',
    projectId: 'auto-shop-web',
    storageBucket: 'auto-shop-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs76sByFLfN8r4cUqLVYyrMZf7K95ZMB0',
    appId: '1:951154264571:ios:e572b85edcd6bd14d3e35e',
    messagingSenderId: '951154264571',
    projectId: 'auto-shop-web',
    storageBucket: 'auto-shop-web.firebasestorage.app',
    iosBundleId: 'com.example.autoShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs76sByFLfN8r4cUqLVYyrMZf7K95ZMB0',
    appId: '1:951154264571:ios:e572b85edcd6bd14d3e35e',
    messagingSenderId: '951154264571',
    projectId: 'auto-shop-web',
    storageBucket: 'auto-shop-web.firebasestorage.app',
    iosBundleId: 'com.example.autoShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBurWVoIlpJYoWYo7auf_K-Xzz2CvClOS4',
    appId: '1:951154264571:web:6e886d7a962b4c57d3e35e',
    messagingSenderId: '951154264571',
    projectId: 'auto-shop-web',
    authDomain: 'auto-shop-web.firebaseapp.com',
    storageBucket: 'auto-shop-web.firebasestorage.app',
  );
}
